### ISSUE TITLE
Unable to unstake VentiHeadz NFTs

### ISSUE THREAD

**Issue by BL4Z3D247** [dperk6/ventiswap-staking-contracts#1]
Hi Dan,

I hope this message finds you well.

I wanted to reach out regarding an issue we've been facing with the VentiHeadz NFT staking platform. Unfortunately, Michael (Johnny Utah) has left the team and community high and dry, and we are in a bit of a bind.

Numerous individuals have invested significant amounts of money into their VentiHeadz NFTs, and it would be immensely beneficial if we could enable the option for them to unstake their VentiHeadz. This would at least allow them to recoup some of their investments.

Could you please look into fixing the staking platform so that people can unstake their VentiHeadz?

We're unable to select the NFT in order for the withdrawal button to be active as you can see by this screenshot.
![Screenshot_2for53](https://github.com/user-attachments/assets/e7f730b2-5d6b-47dc-9280-794994a4bbe5)

Your help in resolving this issue would be greatly appreciated by the entire community.

Thank you in advance for your assistance.

Best regards,  
BL4Z3D247

**Comment by dperk6** [comment]
I'm very sorry. I handed over the front-end code years ago and no longer have it. You should be able to copy the contract code into Remix and use their UI to submit transactions. The functions are documented in the readme.

**Comment by BL4Z3D247** [comment]
Do you possibly have the message you sent to Johnny, it could have the code
attached?

If not, can you point me in the direction of the readme you speak of. Thank
you! 🙏

**Comment by dperk6** [comment]
The readme is the homepage of the repository and is the README.md file in the repo. Grab the interface file (IVentiHeadzStake.sol) from the /interfaces directory and put it in Remix. Then put the contract address in. Remix will give you all the functions. Someone in the community has likely done this before and they should be able to help.

Keep in mind, in the screenshot above you didn't select your NFT. By design you have to click the image first and then the Withdraw button will enable. Not sure if you've tried this.
